version: 2
project_name: wash

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: darwin
        goarch: arm64
        goarm: 7
      - goos: windows
        goarch: arm64
    main: ./cmd/wash/main.go
    binary: wash
    ldflags:
      - -s -w -X github.com/bkidd1/wash-cli/pkg/version.Version={{.Version}}
      - -X github.com/bkidd1/wash-cli/pkg/version.BuildDate={{.Date}}
      - -X github.com/bkidd1/wash-cli/pkg/version.GitCommit={{.Commit}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^ci:'
      - '^chore:'

brews:
  - repository:
      owner: bkidd1
      name: homebrew-tap
      branch: main
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com
    homepage: "https://github.com/bkidd1/wash-cli"
    description: "A development assistant that helps track errors, decisions, and project state"
    license: "MIT"
    install: |
      bin.install "wash" 